---
printWidth: 88
tabWidth: 2
semi: false
singleQuote: false
quoteProps: "consistent"
jsxSingleQuote: false
jsxBracketSameLine: false
trailingComma: "es5"
bracketSpacing: false
arrowParens: "avoid"
endOfLine: "lf"
